### ISSUE TITLE
Entry Request Form: Refresh validators instead of closing form on remote update

### ISSUE THREAD

**Issue by vidalborromeo** [vidalborromeo/eecshelp-beta#11]
v2.0.39

First reported by @eraz in #8.

> Updating the queue settings in any manner (pressing the save button) immediately closes any new request forms in other sessions (forcing the user to start over). If a user was editing a request, the form will disappear and leave the page in an non-interactive state, forcing the user to refresh the page.

**Comment by eraz** [comment]
v2.41
The Request Edit form no longer disappears or leaves the page in a non-interactive state upon queue settings change.
The New Request form still disappears however.

**Comment by vidalborromeo** [comment]
Moving this over to the official public issue tracker.

**Comment by vidalborromeo** [comment]
This issue was moved to vidalborromeo/eecshelp-queue#4
