### ISSUE TITLE
"Hide Description" option covered by submit button

### ISSUE THREAD

**Issue by egoreli** [vidalborromeo/eecshelp-beta#20]
When you are viewing the "create new request" view, the "hide descrpition" panel is covered by the submit button.

- [x] Fix for large media formats
- [x] Fix for medium media formats
- [x] Fix for medium media formats

**Comment by vidalborromeo** [comment]
- [x] Fix for large media formats
- [x] Fix for medium media formats
- [ ] Fix for medium media formats

**Comment by vidalborromeo** [comment]
Fixed in v2.0.101
