### ISSUE TITLE
Feature Request: Topic-Based Queues for Group OH

### ISSUE THREAD

**Issue by skotov** [vidalborromeo/eecshelp-beta#24]
It's often the case that multiple students need help with a particular topic ("What is a pointer? Can we review const? How do I get started on euchre?"). In addition to the regular one on one OH queue, students would find it useful to have queues centered around one topic. Instructors could create queues for various topics and interested students could sign up. Students could also suggest their own topic-based queues; instructors could honor those requests as they see fit. Such a feature would save instructors time, as they could explain a concept once instead of multiple times. It also increases the social nature of office hours, which is particularly beneficial to students in introductory level courses.

**Comment by vidalborromeo** [comment]
This is an interesting idea. I do something like this manually in my own office hours, i.e. I round up all the students who seem to be struggling with the same concept (based on the description in the help requests and/or verbal poll) and explain it to all 10-15 of them at the same time.

I would like to collect more feedback from various staffers and students about what an implementation of this might look like, e.g. UI/UX.

In the mean time, I added a Pro-Tip for a specific technique to the Multiple Queues feature description. This might inspire some staffers to try out the technique, and then from the experience maybe they might have some feedback on what this new feature might look like.
![capture](https://cloud.githubusercontent.com/assets/1500412/20235281/ce7f4616-a85b-11e6-8a7c-10da6c2718d5.PNG)

**Comment by vidalborromeo** [comment]
This issue was moved to vidalborromeo/eecshelp-queue#2

**Comment by vidalborromeo** [comment]
Migrated this over to the official public issue tracker.
