### ISSUE TITLE
Bug/UI Issue: Deleting Moderators

### ISSUE THREAD

**Issue by skotov** [vidalborromeo/eecshelp-beta#25]
In Chrome on MacOS
If you delete a moderator, their entry in the list of moderators does not immediately disappear. This is confusing, as users think their delete was unsuccessful. That said, when I tried to delete the moderator again, I got an error saying that such a moderator does not exist. 

This seems like it might be an easy enough fix, since deleting a course queue causes the queue list to immediately update.

<img width="1002" alt="screen shot 2016-11-08 at 1 13 01 am" src="https://cloud.githubusercontent.com/assets/11304488/20088842/d8c3bc96-a550-11e6-8a9b-a9378c5ade2a.png">

**Comment by vidalborromeo** [comment]
Thanks for the report.

This has now fixed in v2.0.102
