### ISSUE TITLE
GIFs for "helping" animation consume too much CPU

### ISSUE THREAD

**Issue by moosingin3space** [vidalborromeo/eecshelp-beta#28]
On my system, with the page open in Chrome, it pins a core at 25-40% to play the GIFs. This has a very negative effect on battery life.

**Comment by vidalborromeo** [comment]
This is good info to have. Thank you for the report!

The GIFs are easily replaced with something less CPU-intensive. I should be able to address that as soon as tomorrow. Stay tuned.

**Comment by vidalborromeo** [comment]
Fixed in v2.0.119

CPU-intensive gifs have been replaced with very lightweight CSS animations.
