### ISSUE TITLE
Sidebar (left) expands briefly on page load/refresh.

### ISSUE THREAD

**Issue by eraz** [vidalborromeo/eecshelp-beta#3]
v2.30 on Chrome Version 54.0.2840.59 (64-bit)

The sidebar to the left with options "Home", "Roadmap", and "About" opens briefly when loading the page before hiding itself.

Loading the page via links on the site (such as selecting class) or backing/forwarding through the browser history does not appear produce this behavior. The previous page must be something other than the help queue site.

**Comment by vidalborromeo** [comment]
Amusingly this might be a bug in the UI framework I'm using. I specifically set "showOnAttach" to false so that the menu isn't expanded by default. After setting "showOnAttach" to true, the menu no longer pops out on page refresh.

**Comment by vidalborromeo** [comment]
UPDATE:
It's a CSS media query thing!
When "showOnAttach==true":
- The SideNav _does_ expand by default on a large enough window size.
- The SideNav _doesn't_ expand by default on window sizes smaller than that.

When "showOnAttach==false":
- The SideNav _always_ pops out briefly before disappearing.

This _still_ looks like a bug in the framework, so I filed a bug report with them.

@eraz, in the mean time what do you think the behavior should be?

**Comment by vidalborromeo** [comment]
UPDATE:
Heard back from the makers of the framework. It _IS_ a bug. Turns out someone first reported it just 8 days ago.

**Comment by vidalborromeo** [comment]
I have a workaround. Will be added in version 2.40

**Comment by eraz** [comment]
@vidalborromeo Whoops, typed a response but forgot to submit it. I would prefer that the sidebar remain hidden unless opened by the user by clicking the menu button on the top left. However, width is not really lacking in the current site design, so I wouldn't mind having it open by default, though it throws off the balance a bit.

**Comment by vidalborromeo** [comment]
Update:
As of 2.0.53, the menu should be closed by default now - without flashing.
