### ISSUE TITLE
White shade covers page when site is loading.

### ISSUE THREAD

**Issue by eraz** [vidalborromeo/eecshelp-beta#4]
v2.0.30 on Chrome Version 54.0.2840.59 (64-bit)

When refreshing the page, a pale white shade briefly covers the site before the page is reloaded. This shade is accompanied by a loading animation at the center of the screen (a "spinning" blue line). This is very distracting, especially when navigating the site quickly.

This white shade flashes (very) briefly when clicking on any of the classes listed to expand them, but only once per class link (does not happen if class name is clicked again unless the page is refreshed). Toggling an office hour status as "closed" or "open" also produces this behavior. This appears to happen when the site attempts to load something for the first time. This does not happen for the "+ Request" or "+ Announce" buttons on a queue page.

**Comment by vidalborromeo** [comment]
The modal progress indicator is displayed during user-initiated asynchronous requests to the server. It is just a means (one of several) of indicating to a user that their action was:
1) Detected/Triggered
2) Is still in progress.
The modal aspect also serves as a way to lock the UI during asynchronous requests to the server. More specifically, to prevent multiple (potentially conflicting) async requests to be in the air at the same time. Without it, under the right conditions and network latency, it's possible for a user to click their way into an inconsistent state.
The reason the progress indicator doesn't show up for "+ Request" or "+ Announce" is that there is no need for a trip to the server to show those forms.

I'm open to discussing alternate approaches.
(Will close this issue for now.)
