### ISSUE TITLE
Tooltips do not disappear after clicking on button.

### ISSUE THREAD

**Issue by eraz** [vidalborromeo/eecshelp-beta#5]
v2.30 on Chrome Version 54.0.2840.59 (64-bit)

The grey box next to the "+ Request" and "+ Announce" buttons on a queue page does not disappear if the buttons are clicked. The mouse must leave the button, then re-hover over the button for the tooltip to disappear appropriately when the mouse leaves the button once more.

Firefox ESR 45.4.0 does not appear to produce this behavior.

**Comment by vidalborromeo** [comment]
I'm seeing this as well.
Looks like it has to do with the browser's internal event-handling, i.e. "mouseout" isn't fired when a modal dialog is displayed over the widget.

For the time being I just removed the tooltip from those buttons. 

Fix is deployed in v2.38.
