### ISSUE TITLE
Cannot sign in via Chrome on Android.

### ISSUE THREAD

**Issue by eraz** [vidalborromeo/eecshelp-beta#6]
v2.30 in Chrome Version 53.0.2785.124 on Android 6.0.1.

Navigating to the main page opens a new tab (popup) which prompts for login details, but the page does not reload after providing said details. A manual page refresh only resets the situation.

**Comment by vidalborromeo** [comment]
Oy.
Mobile browsers, why dost thou hateth me?

This could be addressed by the fix for https://github.com/vidalborromeo/eecshelp-beta/issues/10.

**Comment by vidalborromeo** [comment]
Update:
This is indeed fixed by the fix for #10. The new login flow is much much smoother.
