### ISSUE TITLE
"Being helped by" duplicates after edits to request.

### ISSUE THREAD

**Issue by eraz** [vidalborromeo/eecshelp-beta#7]
v2.30 in Chrome Version 54.0.2840.59 (64-bit) and Firefox ESR 45.4.0.

If a request is updated after an instructor is assigned to the request, the instructor's name is duplicated in the "Being Helped By:" section of the request. Two duplicates appear in the editor's session, one duplicate in another window (but same session), no duplicates on others' sessions. The problem appears to be cosmetic as they do not persist after a page refresh. This effect is repeatable.

![screenshot from 2016-10-17 17-12-38](https://cloud.githubusercontent.com/assets/9088415/19455923/102c5cd0-948d-11e6-8ac8-5273db4fdf1e.png)

**Comment by vidalborromeo** [comment]
Aha!
I knew I had seen that happen. Thank you!

**Comment by vidalborromeo** [comment]
Fix is part of version 2.39. Will deploy later with some other fixes.
